# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$line_break\
$character\
"""

[time]
disabled = false
time_format = "%-I:%M:%S %p"
style = "fg:#a0a9cb"
format = '[$time]($style) '

[directory]
truncation_length = 0

[git_branch]
style = "yellow"
format = '[\($branch(:$remote_branch)]($style)\) '

[git_metrics]
disabled = false

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](red)"
